Extended the description of oplogOnly command
percona/pbm-docs pull request #118
Opened 2023-06-26 18:46 UTC by nastena1606

modified:   docs/reference/pitr-options.md
	modified:   docs/usage/oplog-replay.md
	modified:   docs/usage/start-backup.md

2023-06-28 07:52 UTC, sandraromanchenko requested changes

2023-06-28 07:52 UTC, sandraromanchenko commented on docs/reference/pitr-options.md
> +Controls whether the base backup is required to start [Point-in-Time recovery oplog slicing](../features/point-in-time-recovery.md#oplog-slicing). When set to true, Percona Backup for MongoDB saves o
> When set to true, this option also instructs Percona Backup for MongoDB to retrospectively save the oplog slices for the time when a physical backup was running. 

That is not true, please remove this part

2023-06-28 07:52 UTC, sandraromanchenko commented on docs/usage/start-backup.md
> +     During a *physical* backup, Percona Backup for MongoDB stops [point-in-time recovery oplog slicing](../features/point-in-time-recovery.md#oplog-slicing), copies the contents of the `dbpath` dire
```suggestion
     During a *physical* backup, Percona Backup for MongoDB stops [point-in-time recovery oplog slicing] if it's enabled (../features/point-in-time-recovery.md#oplog-slicing), copies the contents of the `dbpath` directory (data and metadata files, indexes, journal and logs) from every shard and config server replica set to the backup storage.
```

2023-06-28 10:54 UTC, sandraromanchenko approved these changes

2023-06-30 09:35 UTC, olexandr-havryliak approved these changes

2023-06-30 09:45 UTC, merged