PBM-1133 Added a config option to support path-style requests for S3 …
percona/pbm-docs pull request #125
Opened 2023-07-06 15:35 UTC by nastena1606

…buckets

	modified:   docs/reference/configuration-options.md

2023-07-07 05:44 UTC, defbin approved these changes

2023-07-10 09:46 UTC, sandraromanchenko requested changes

2023-07-10 09:46 UTC, sandraromanchenko commented on docs/reference/configuration-options.md
> +When enabled, PBM uses the [path-style URLs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access) for accessing the S3 bucket. Otherwise, it sends virtual-host
@defbin @nastena1606 is it vice versa? From doc - this option means "whether to force path style URLs for S3 object" and in code this option is set to True by default. 
```suggestion
When enabled, PBM uses the [path-style URLs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access) for accessing the S3 bucket (default). Otherwise, it sends virtual-hosted–style requests.
```

2023-07-10 12:31 UTC, defbin approved these changes

2023-07-10 15:54 UTC, defbin approved these changes

2023-07-13 13:22 UTC, merged