PBM-755 Added physical backups description into docs
percona/pbm-docs pull request #13
Opened 2022-02-22 18:24 UTC by nastena1606

modified:   source/index.rst
	modified:   source/initial-setup.rst
	modified:   source/installation.rst
	modified:   source/intro.rst
	modified:   source/pbm-commands.rst
	modified:   source/point-in-time-recovery.rst
	modified:   source/running.rst
        new file: source/backup-types.rst

2022-03-23 14:04 UTC, spron-in approved these changes

2022-04-15 09:21 UTC, sandraromanchenko commented on source/running.rst
> +   Physical backup information is not available in pbm logs.
It's partially true - it's possible to check logs about physical backup via 'pbm logs', but on the other hand info about restore from physical backup isn't accessible using the mentioned command. Should we make a note more specific?

2022-04-15 09:21 UTC, sandraromanchenko commented on source/index.rst
> +* For *physical* backups - `Percona Server for MongoDB <https://www.percona.com/software/mongo-database/percona-server-for-mongodb>`_ or higher with `MongoDB Replication <https://docs.mongodb.com/man
There is no actual version of PSMDB defined, is it correct?

2022-04-15 09:55 UTC, nastena1606 commented on source/index.rst
> +* For *physical* backups - `Percona Server for MongoDB <https://www.percona.com/software/mongo-database/percona-server-for-mongodb>`_ or higher with `MongoDB Replication <https://docs.mongodb.com/man
Good point, thank you !

2022-04-15 09:55 UTC, nastena1606 commented on source/running.rst
> +   Physical backup information is not available in pbm logs.
Amended

2022-04-15 10:52 UTC, sandraromanchenko requested changes

2022-04-15 10:52 UTC, sandraromanchenko commented on source/index.rst
> +* For *physical* backups - `Percona Server for MongoDB <https://www.percona.com/software/mongo-database/percona-server-for-mongodb>`_ v4.2 or higher with `MongoDB Replication <https://docs.mongodb.co
Not good enough XD 
Backup cursor was introduced in 4.2.15-16, 4.4.6-8, 5.0+ physical backups won't work with versions which are lower

2022-04-18 13:48 UTC, sandraromanchenko approved these changes

2022-04-18 13:49 UTC, merged