PBM-1141 Documented deleted backup by type
percona/pbm-docs pull request #153
Opened 2024-02-07 10:00 UTC by nastena1606

modified:   docs/usage/delete-backup.md
	modified:   docs/usage/schedule-backup.md
	modified:   mkdocs-base.yml

2024-02-21 20:59 UTC, sleto-it requested changes

2024-02-21 20:59 UTC, sleto-it commented on docs/reference/pbm-commands.md
> +| `--dry-run`              | Prints the list of oplog slices to be deleted without deleting them. You can use the flag to check what exactly will be deleted. |
was the dry-run option added in 2.4.0? If yes, can we mention (as we did for the --type option)? thank you

2024-02-26 10:48 UTC, sleto-it commented on docs/reference/pbm-commands.md
> +| `--dry-run`              | Prints the list of oplog slices to be deleted without deleting them. You can use the flag to check what exactly will be deleted. |
Thanks for the additional commit. Resolving the conversation.

2024-02-27 13:56 UTC, sandraromanchenko approved these changes

2024-03-05 14:20 UTC, merged