PBM-907 Doc: Don't stop PITR during backup
percona/pbm-docs pull request #154
Opened 2024-02-08 11:01 UTC by nastena1606

modified:   docs/features/point-in-time-recovery.md
	modified:   docs/reference/backup-options.md
	modified:   docs/usage/restore.md
	modified:   docs/usage/start-backup.md
	modified:   mkdocs-pdf.yml

2024-02-08 11:03 UTC, defbin commented on docs/features/point-in-time-recovery.md
> +    * A full backup snapshot is required. Starting with version [2.4.0](../release-notes/2.4.0.md), it can be a logical, a physical or a base incremental backup. Make sure that a [backup exists](../u
```suggestion
    * A full backup snapshot is required. Starting with version [2.4.0](../release-notes/2.4.0.md), it can be a logical, a physical or an incremental backup. Make sure that a [backup exists](../usage/list-backup.md). See the [Make a backup](../usage/start-backup.md) guide to make a backup snapshot.
```

2024-02-08 11:04 UTC, defbin commented on docs/features/point-in-time-recovery.md
> +If you just enabled point-in-time recovery, it requires 10 minutes for the first slice to appear in the [`pbm list`](../reference/pbm-commands.md#pbm-list) output.
I would use "oplog range" instead of "slice"

2024-02-08 11:08 UTC, defbin commented on docs/reference/backup-options.md
> +The duration (in minutes) of oplog slices saved with the logical backup snapshot. By default, the duration of backup oplog slices equals to the value defined for the [`pitr.oplogSpanMin`](pitr-option
```suggestion
The duration (in minutes) of oplog slices saved with the logical backup snapshot. By default, the duration of backup oplog slices equals to the value defined for the [`pitr.oplogSpanMin`](pitr-options.md#pitroplogspanmin) option (default - 10 minutes). You can reduce the duration in heavy-loaded environments. Note that setting the duration to shorter periods may slightly increase the overall backup execution time.
```

2024-02-08 11:10 UTC, defbin commented on docs/usage/start-backup.md
> +     Starting with [2.0.4](../release-notes), PBM doesn't stop [point-in-time recovery oplog slicing](../features/point-in-time-recovery.md#oplog-slicing), if it's enabled, but runs it in parallel. T
```suggestion
     Starting with [2.4.0](../release-notes), PBM doesn't stop [point-in-time recovery oplog slicing](../features/point-in-time-recovery.md#oplog-slicing), if it's enabled, but runs it in parallel. This ensures [point-in-time recovery](pitr-tutorial.md) to any timestamp if it takes too long (e.g. hours) to make a backup snapshot.
```

2024-02-08 15:38 UTC, defbin commented on docs/features/point-in-time-recovery.md
> +    * A full backup snapshot is required. Starting with version [2.4.0](../release-notes/2.4.0.md), it can be a logical, a physical or a base incremental backup. Make sure that a [backup exists](../u
yes

2024-02-12 09:11 UTC, nastena1606 commented on docs/features/point-in-time-recovery.md
> +If you just enabled point-in-time recovery, it requires 10 minutes for the first slice to appear in the [`pbm list`](../reference/pbm-commands.md#pbm-list) output.
We have slices everywhere so let's stick to this naming for now. We can improve it in next iteration

2024-02-17 13:57 UTC, defbin approved these changes

2024-02-26 12:19 UTC, sandraromanchenko requested changes

2024-02-26 12:19 UTC, sandraromanchenko commented on docs/usage/restore.md
> +    3. [Enable point-in-time recovery](../features/point-in-time-recovery.md#enable-point-in-time-recovery)
IF REQUIRED

2024-02-26 12:19 UTC, sandraromanchenko commented on docs/usage/restore.md
> +    5. Make a fresh backup to serve as the new base for future restores.
```suggestion
    5. We recommend to make a fresh backup to serve as the new base for future restores.
```

2024-02-26 12:19 UTC, sandraromanchenko commented on docs/usage/restore.md
> +    6. [Enable point-in-time recovery](../features/point-in-time-recovery.md#enable-point-in-time-recovery) if needed.
IF REQUIRED

2024-03-05 14:21 UTC, merged