PBM-1237 Release notes 2.4.0
percona/pbm-docs pull request #156
Opened 2024-02-26 15:08 UTC by nastena1606

modified:   _resource/overrides/partials/copyright.html
	modified:   docs/release-notes.md
	new file:   docs/release-notes/2.4.0.md
	modified:   mkdocs-base.yml
	modified:   mkdocs-pdf.yml
	modified:   variables.yml

2024-02-27 13:30 UTC, sandraromanchenko approved these changes

2024-02-28 13:34 UTC, janwieremjewicz approved these changes

2024-03-04 11:56 UTC, sleto-it requested changes

2024-03-04 11:56 UTC, sleto-it commented on docs/release-notes/2.4.0.md
> +* You can now delete backup snapshots of a specific type. This helps you better meet the organization's policy and implement the backup strategy.
Hi! Please can we be a bit more specific here? Internal and external users will look at this entry to understand more what has been introduced or changed - but as it is now they do not get much details in my opinion. It would be nice to mention the new options (`--type` and `--dry-run`) if I am not mistaken. And also it would be nice to add the link to the delete backup reference documentation (that we have changed with this release, in another PR) - in preview here: https://pbm-docs-pr-153.onrender.com/reference/pbm-commands.html#pbm-delete-backup . Thank you

2024-03-04 11:56 UTC, sleto-it commented on docs/release-notes/2.4.0.md
> +* Percona Backup for MongoDB packages are available for ARM64 architectures, enabling users to install it on premises. The ARM64 packages are available for the following operating systems:
"enabling users to install it on premise" - this is a bit confusing to me. It is already possible to install it on prem, not sure I get this 100%.

Also "Percona Backup for MongoDB packages are available for ARM64 architectures" if written this way it is not clear that the packages on this arch are in addition to the others we have on the other arch. We can use - just of an example - an expression like: "Starting from this version Percona Backup for MongoDB packages are available also on the ARM64 architectures" (with "also") - something that makes more clear that this architecture is a new arch that we have added. Thanks

2024-03-04 14:18 UTC, sleto-it commented on docs/release-notes/2.4.0.md
> +* [PBM-1223](https://perconadev.atlassian.net/browse/PBM-1223) - Fixed the issue with PBM not backing up oplog from the oldest active transaction timestamp
I am checking something internally on this one and will get back - as we might need to details things with more details - as this bug can be scaring. But I know the trigger conditions for are rare, and very specific, as far as I understad. So we might want to say something "Under rare conditions it can happen that ... this is now fixed". Or something similar.

2024-03-04 14:42 UTC, sandraromanchenko approved these changes

2024-03-04 14:48 UTC, sleto-it commented on docs/release-notes/2.4.0.md
> +* Percona Backup for MongoDB packages are available for ARM64 architectures, enabling users to install it on premises. The ARM64 packages are available for the following operating systems:
thank you for the new commit.  Marking resolved.

2024-03-04 15:01 UTC, sleto-it commented on docs/release-notes/2.4.0.md
> +* You can now delete backup snapshots of a specific type. This helps you better meet the organization's policy and implement the backup strategy.
thanks for the new commit. we can consider  replacing ` --dry-run flag` with `--dry-run` flag - but this is minor thing. resolving.

2024-03-04 17:56 UTC, sleto-it commented on docs/release-notes/2.4.0.md
> +* [PBM-1223](https://perconadev.atlassian.net/browse/PBM-1223) - Fixed the issue with PBM not backing up oplog from the oldest active transaction timestamp
resolving for now.

2024-03-04 17:56 UTC, sleto-it approved these changes

2024-03-05 14:28 UTC, merged