PBM-1310 Release notes 2.5.0
percona/pbm-docs pull request #176
Opened 2024-05-08 12:00 UTC by nastena1606

modified:   docs/release-notes.md
	new file:   docs/release-notes/2.5.0.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-05-08 12:15 UTC, igroene requested changes

2024-05-08 12:15 UTC, igroene commented on docs/release-notes/2.5.0.md
> +Percona Backup for MongoDB is a distributed, low-impact solution for consistent backups of MongoDB sharded clusters and replica sets. This is a tool for creating consistent backups across a MongoDB s
this paragraphs has two sentences which are kinda redundant. Why not say instead:
```
Percona Backup for MongoDB is a distributed, low-impact solution for creating consistent backups of MongoDB sharded clusters and replica sets, and for restoring those backups to a specific point in time.
```

2024-05-08 12:15 UTC, igroene commented on docs/release-notes/2.5.0.md
> +* You can now restore the desired subset of [custom databases with users and roles](../features/selective-backup.md#restore-a-database-with-users-and-roles) created in them. This is useful for deploy
the link referenced above doesn't seem to exist in this branch

2024-05-08 12:15 UTC, igroene commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
Instead I would say:
``` Previous versions of PBM required that readConcern and writeConcern levels are set to majority in MongoDB.  You can now explicitly override this behaviour, which allows backing up Primary-Secondary-Arbiter topologies that run with writeConcern majority disabled.```

2024-05-08 12:40 UTC, nastena1606 commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
I believe this requirement is still valid. @boris-ilijic @sandraromanchenko please confirm

2024-05-08 12:40 UTC, nastena1606 commented on docs/release-notes/2.5.0.md
> +* You can now restore the desired subset of [custom databases with users and roles](../features/selective-backup.md#restore-a-database-with-users-and-roles) created in them. This is useful for deploy
Yes, it will work afetr the merge of all PRs related to the release. The doc changes are in https://github.com/percona/pbm-docs/pull/171

2024-05-08 15:04 UTC, nastena1606 commented on docs/release-notes/2.5.0.md
> +Percona Backup for MongoDB is a distributed, low-impact solution for consistent backups of MongoDB sharded clusters and replica sets. This is a tool for creating consistent backups across a MongoDB s
Fixed

2024-05-09 08:45 UTC, boris-ilijic commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
I am fine to have this in the release highlights, 1st sentence for sure, but 2nd one is not completely clear for me:
'…Primary-Secondary-Arbiter topologies that **run with writeConcern majority disabled**' 

So to be sure that we were testing everything and that we are referring to the same thing,  I can think that you are referring here to:
* PSA with failed S (no majority because of failing member)
* PSA with non-voting S (majority is 1)
* PSA with lagging S (majority cannot be reached in 'normal' execution time)  

@igroene did you refer to this configurations or to something else/more ?
If yes, for me it'll be clearer to say: '…Primary-Secondary-Arbiter topologies that run without write majority'

BTW, there are other topologies in which 'lowering' R/W/Concern can be beneficial, so it's not just PSA, and such one is described in:  PBM-799 description. But probably we do not need to mention that in highlights.

2024-05-09 12:22 UTC, igroene commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
Sorry I meant to say here "read concern majority disabled".  This is related to https://www.mongodb.com/docs/v3.6/reference/read-concern-majority/#disable-read-concern-majority

2024-05-09 13:55 UTC, igroene approved these changes
LGTM

2024-05-09 14:11 UTC, boris-ilijic commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
Yes, but that option is obsolete in Mongo4.x and in Mongo5 and above is not configurable anymore: https://www.mongodb.com/docs/manual/release-notes/5.0-compatibility/#enablemajorityreadconcern-is-not-configurable. 
Also we double checked that option with customer, please see this thread for details: https://perconadev.atlassian.net/browse/PBM-1159?focusedCommentId=409702

In that case I strongly recommend to not mention that use case in highlights, even more because we didn't test it, because Mongo4.x is EOL. My recommendation is to take 1st Ivan's / 2nd Anastasia'a sentences then.

2024-05-09 14:14 UTC, igroene commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
we still have customers running 4.x and PSA topologies, and that is actually the reason why we are implementing this change to allow them to still use PBM. So why would we not mention it in the release notes?

2024-05-09 14:32 UTC, boris-ilijic commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
My point was to mention use case with explicit obsolete option (`--enableMajorityReadConcern`). But if that's important for us I do not have concerns. We'll do additional testing on Monday on 4.2 with disabled that option, but imo that should work.

2024-05-13 10:54 UTC, janwieremjewicz requested changes

2024-05-13 10:54 UTC, janwieremjewicz commented on docs/release-notes/2.5.0.md
> +* [PBM-1258](https://perconadev.atlassian.net/browse/PBM-1258) Improve the resync from storage logic to be triggered only upon changes in the configuration file.
missing '-' after the Jira ID

2024-05-13 10:54 UTC, janwieremjewicz commented on docs/release-notes/2.5.0.md
> +* Previous versions of PBM required that `readConcern` and `writeConcern` are set to `majority` in MongoDB. You can now explicitly override this behavior, and thus, ensure backups in Primary-Secondar
Can we link to such requirement in the documentation and mark it there that as of 2.5.0 it's not required?

2024-05-15 05:30 UTC, defbin approved these changes

2024-05-15 05:51 UTC, sandraromanchenko requested changes

2024-05-15 05:51 UTC, sandraromanchenko commented on mkdocs-base.yml
> +          cover_subtitle: 2.5.0 (May 14, 2024)
```suggestion
          cover_subtitle: 2.5.0 (May 16, 2024)
```

2024-05-15 06:15 UTC, sandraromanchenko commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
It works just fine with ReadConcern majority disabled on DB level (PSMDB 4.4)
```
pbm-agent --mongodb-uri="mongodb://XXX:XXX@testdb:27017/?authSource=admin"
Version:   2.5.0
Platform:  linux/amd64
GitCommit: be273eee454fbbb2bd269bb46c24078b35d98894
GitBranch: release-2.5.0
BuildTime: 2024-05-15_05:58_UTC
GoVersion: go1.22.3
2024-05-15T05:56:29.000+0000 I starting PITR routine
2024-05-15T05:56:29.000+0000 I node: rs1/localhost:27017
2024-05-15T05:56:29.000+0000 E [pitr] init: get conf: get: (ReadConcernMajorityNotEnabled) Majority read concern is not enabled.
2024-05-15T05:56:29.000+0000 I listening for the commands
2024-05-15T05:56:29.000+0000 E listening commands: watch the cmd stream: (ReadConcernMajorityNotEnabled) Majority read concern is not enabled.
==============================================
pbm-agent --mongodb-uri="mongodb://XXX:XXX@testdb:27017/?authSource=admin&w=1&readConcernLevel=local"
2024-05-15T05:57:47.000+0000 I pbm-agent:
Version:   2.5.0
Platform:  linux/amd64
GitCommit: be273eee454fbbb2bd269bb46c24078b35d98894
GitBranch: release-2.5.0
BuildTime: 2024-05-15_05:58_UTC
GoVersion: go1.22.3
2024-05-15T05:57:47.000+0000 I starting PITR routine
2024-05-15T05:57:47.000+0000 I node: rs1/localhost:27017
2024-05-15T05:57:47.000+0000 I listening for the commands
==============================================
```
Although I'd still NOT mention this particular option in release highlights as Mongo4.x is EOL. The main reason for implementing this change is to support scenarios when RS looses majority for some reason and customer still should have an ability to use PBM. Claim that PBM supports PSA topologies with readConcern majority disabled supposes that PBM supports PSMDB version lower that 5.0 and while we're still technically testing PBM with 4.4, I'm not sure that in PSMDB 4.2 + PBM 2.5.0 combination even basic functionality would work not mentioning new feature.

2024-05-15 08:06 UTC, sandraromanchenko approved these changes

2024-05-15 08:51 UTC, boris-ilijic approved these changes

2024-05-15 12:01 UTC, nastena1606 commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
@igroene @janwieremjewicz Are you OK with the updated wording?

2024-05-15 12:06 UTC, igroene commented on docs/release-notes/2.5.0.md
> +* By design, PBM requires the majority level of readConcern and writeConcern in MongoDB. If your cluster is configured to operate without the majority or loses it for some reason, you can now overrid
yes

2024-05-16 13:11 UTC, merged