PBM-1333 Warning about breaking ACID during selective restore
percona/pbm-docs pull request #182
Opened 2024-06-07 13:47 UTC by nastena1606

2024-06-13 10:58 UTC, defbin approved these changes

2024-06-13 12:19 UTC, igroene requested changes
can you mention exactly what happens? "break ACID" is not clear... let's say I have a tx involving collections A and B, if I selective restore collection A does it mean data on collection B will be "corrupted"?

2024-06-13 12:35 UTC, defbin commented on docs/features/selective-backup.md
> +    Multi-collection transactions and time series collections are not supported. However, if you use them and try to make a selective restore, it may break ACID because not all operations with this t
```suggestion
    Multi-collection transactions and time series collections are not supported. However, if you use them and try to make a selective restore, it may break ACID because not all operations with this transaction are restored. PBM only applies oplog records that relate to the selected namespace(s). Thus, from the transaction's point of view, the data consistency may be broken.
    For example, if there is a transaction that contains changes for collections A and B, but only A is selected, PBM applies ops only for A and ignores B, which means the transaction is not be fully applied.
```

2024-06-17 10:02 UTC, defbin approved these changes

2024-06-17 12:37 UTC, igroene approved these changes
LGTM

2024-06-17 12:40 UTC, merged