PBM-1228 Documented multiple storages for backups
percona/pbm-docs pull request #187
Opened 2024-06-26 07:10 UTC by nastena1606

modified:   docs/features/comparison.md
	new file:   docs/features/multi-storage.md
	modified:   docs/reference/pbm-commands.md
	modified:   mkdocs-base.yml

2024-08-13 10:39 UTC, defbin approved these changes

2024-08-14 08:12 UTC, sandraromanchenko requested changes

2024-08-14 08:12 UTC, sandraromanchenko commented on docs/features/multi-storage.md
> +3. PBM keeps backups and oplog ranges only on the main storage. For any external storage, PBM saves only backup snapshots.
Let's reword this sentence, it's not clear enough

2024-08-14 12:16 UTC, sandraromanchenko requested changes

2024-08-14 12:16 UTC, sandraromanchenko commented on docs/features/multi-storage.md
> +3. PBM saves point-int-time recovery oplog ranges only on the main storage. Backups are saved on the storage that you define when starting a backup.
```suggestion
3. PBM saves point-in-time recovery oplog ranges only on the main storage. Backups are saved on the storage that you define when starting a backup. 
```

2024-08-14 12:16 UTC, sandraromanchenko commented on docs/features/multi-storage.md
> +8.	You can delete backups from external storages only by name using the `pbm delete-backup <backup-name>` command. Bulk deletion of backups older than the specified time is supported only for the mai
```suggestion
5. The whole incremental chain must be stored on the same storage. To change the storage for incremental backups, you must start a new backup chain with the incremental base backup on the new storage.
6. To restore from a backup on external storage, pbm-agents must have read permissions on it.
7. To make a point-in-time recovery, you must specify the backup name via the `--base-snapshot` flag. Without it, PBM searches for the base backup on the main storage.
8. You can delete backups from external storages only by name using the `pbm delete-backup <backup-name>` command. Bulk deletion of backups older than the specified time is supported only for the main storage.
```

2024-08-14 12:25 UTC, sandraromanchenko approved these changes

2024-09-02 09:01 UTC, merged