PBM-1043 PITR node priority
percona/pbm-docs pull request #190
Opened 2024-07-15 09:04 UTC by nastena1606

docs/features/point-in-time-recovery.md

2024-08-13 07:55 UTC, boris-ilijic approved these changes
Very nice write, but please see 2 comments. In any case I am fine with it.

2024-08-13 07:55 UTC, boris-ilijic commented on docs/features/point-in-time-recovery.md
> +By default, the `pbm-agent` to save oplog slices is selected randomly across secondary replica set members. The primary node is selected last, if none of the secondaries is responding.
```suggestion
Up to the PBM v2.6.0, the `pbm-agent` to save oplog slices is selected randomly across replica set members. All nodes have an equal chance to start oplog slicing. 
```

2024-08-13 07:55 UTC, boris-ilijic commented on docs/features/point-in-time-recovery.md
> +The `pbm-agent` starts [saving consecutive slices of the oplog](#oplog-slicing) periodically. A method similar to the way replica set nodes elect a new primary is used to select the `pbm-agent` that
`A method similar to the way replica set nodes elect a new primary is used to select...`
This is from technical perspective correct on very high level, when we go into technical discussion (not detailed one) this statement is not valid.

If we want to keep it and make it correct, this can be the way to express it:
`A method similar to the way replica set with defined node's priority elects a new primary is used to select ...`
If it sounds too complex I would omit it completely, so it's up to you.

2024-08-13 13:39 UTC, boris-ilijic commented on docs/features/point-in-time-recovery.md
> +The `pbm-agent` starts [saving consecutive slices of the oplog](#oplog-slicing) periodically. A method similar to the way replica set nodes elect a new primary is used to select the `pbm-agent` that
Yes, that's right, in that case it is valid. So I am find to keep original version, I was reading it wrongly.

2024-08-13 13:52 UTC, boris-ilijic commented on docs/features/point-in-time-recovery.md
> +The `pbm-agent` starts [saving consecutive slices of the oplog](#oplog-slicing) periodically. A method similar to the way replica set nodes elect a new primary is used to select the `pbm-agent` that
But again after I think more, it is wrong also in case when node priority is not explicitly defined. E.g. mongo will never elect hidden as primary, but PBM will choose hidden as oplog slicer. Also underlaying protocol is completely different, which made initial confusion to me. Imo, that comparison is not in place anyhow.

2024-08-14 06:07 UTC, sandraromanchenko commented on docs/features/point-in-time-recovery.md
> +The `pbm-agent` starts [saving consecutive slices of the oplog](#oplog-slicing) periodically. A method similar to the way replica set nodes elect a new primary is used to select the `pbm-agent` that
I do agree with Boris, this comparison is irrelevant here, can we remove part about "method similar to the way replica set nodes elect a new primary"? PBM agent is just randomly selected among nodes with the same priority either they are default, or user-defined.

2024-08-14 06:18 UTC, sandraromanchenko requested changes

2024-08-14 06:18 UTC, sandraromanchenko commented on docs/features/point-in-time-recovery.md
> +* arbiter or hidden node - priority 2
```suggestion
* hidden node - priority 2
```
We can't take PITR from arbiter

2024-08-14 08:00 UTC, sandraromanchenko approved these changes

2024-09-02 08:58 UTC, merged