PBM-1363 Release notes 2.6.0
percona/pbm-docs pull request #198
Opened 2024-08-13 11:24 UTC by nastena1606

modified:   docs/release-notes.md
	new file:   docs/release-notes/2.6.0.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-08-13 11:39 UTC, defbin approved these changes

2024-08-14 07:23 UTC, boris-ilijic approved these changes

2024-08-14 13:40 UTC, sandraromanchenko requested changes

2024-08-14 13:40 UTC, sandraromanchenko commented on docs/release-notes/2.6.0.md
> +* [PBM-1228](https://perconadev.atlassian.net/browse/PBM-1228) - Support multiple storage for backups and restores.
Why https://perconadev.atlassian.net/browse/PBM-1300 didn't make it to new features?

2024-08-14 13:40 UTC, sandraromanchenko commented on docs/release-notes/2.6.0.md
> +* [PBM-1364](https://perconadev.atlassian.net/browse/PBM-1364) - Ensure PITR routine is fully operational after the cluster leader restart
```suggestion
```
Internal ticket for epic, no need to put in RN

2024-08-14 13:45 UTC, nastena1606 commented on docs/release-notes/2.6.0.md
> +* [PBM-1228](https://perconadev.atlassian.net/browse/PBM-1228) - Support multiple storage for backups and restores.
Do we add Epics? Or should we? @radoslawszulgo what do you say, shall we add Epics and implementation tickets to RN or go with either ticket type?

2024-08-14 13:56 UTC, radoslawszulgo approved these changes

2024-08-14 13:56 UTC, radoslawszulgo commented on docs/release-notes/2.6.0.md
> +With snapshot-based physical backups now generally available, you can use this functionality in production environments and enjoy all the benefits of faster restores from snapshots with almost immedi
Please add the link to learn more about snapshot-based physical backup ;)

2024-08-15 08:57 UTC, nastena1606 commented on docs/release-notes/2.6.0.md
> +With snapshot-based physical backups now generally available, you can use this functionality in production environments and enjoy all the benefits of faster restores from snapshots with almost immedi
Done

2024-08-19 10:46 UTC, radoslawszulgo commented on docs/release-notes/2.6.0.md
> +* [PBM-1228](https://perconadev.atlassian.net/browse/PBM-1228) - Support multiple storage for backups and restores.
IMHO it's not needed. We've already described this in the highlights. We don't need to mention it in release notes unless we provide valuable information in the Jira ticket.

2024-08-19 10:47 UTC, radoslawszulgo commented on docs/release-notes/2.6.0.md
> +
## Join Percona Squad!
Participate in monthly SWAG raffles, get early access to new product features, and invite-only ”ask me anything” sessions with database performance experts. Interested? Fill in the form at [squad.percona.com/mongodb](http://squad.percona.com/mongodb)

2024-08-21 16:40 UTC, sandraromanchenko requested changes

2024-08-21 16:40 UTC, sandraromanchenko commented on docs/release-notes/2.6.0.md
> +* [PBM-1377](https://perconadev.atlassian.net/browse/PBM-1377) - Fixed the  issue with backups failing to start when there is insufficient oplog range for PITR
```suggestion
* [PBM-1377](https://perconadev.atlassian.net/browse/PBM-1377) - Fixed the issue with backups failing to start by implementing measures to avoid conflicts with the PITR procedure
```

2024-08-21 16:40 UTC, sandraromanchenko commented on docs/release-notes/2.6.0.md
> +* [PBM-1239](https://perconadev.atlassian.net/browse/PBM-1239) - Fixed the issue with logical backups failing on GCS by using the libraries that support retries
```suggestion
* [PBM-1239](https://perconadev.atlassian.net/browse/PBM-1239) - Fixed the issue with logical backups failing on GCS by utilizing libraries that provide retry functionality.
```

2024-08-21 16:40 UTC, sandraromanchenko commented on docs/release-notes/2.6.0.md
> +* [PBM-1348](https://perconadev.atlassian.net/browse/PBM-1348) - Fixed the incorrect behavior of the shell when using the `--wait` for the JSON output in pbm commands
```suggestion
* [PBM-1348](https://perconadev.atlassian.net/browse/PBM-1348) - Fixed the incorrect behavior of PBM CLI where the `--wait` option was causing incorrect behavior with `pbm backup` command while generating JSON output
```

2024-08-21 17:09 UTC, sandraromanchenko commented on mkdocs-base.yml
> +          cover_subtitle: 2.6.0 (August 22, 2024)
```suggestion
          cover_subtitle: 2.6.0 (September 2, 2024)
```

2024-08-21 17:14 UTC, sandraromanchenko approved these changes

2024-08-21 17:14 UTC, sandraromanchenko commented on variables.yml
> +  2_6_0: 2024-08-22
```suggestion
  2_6_0: 2024-09-02
```

2024-08-30 07:35 UTC, sleto-it commented on docs/release-notes/2.6.0.md
> +With [snapshot-based physical backups](../features/snapshots.md) now generally available, you can use this functionality in production environments and enjoy all the benefits of faster restores from
Hi! In `snapshots.md` page, under `Considerations`, point 1. Please consider to mention that the feature is GA starting from v2.6.0. Thanks!

2024-08-30 07:40 UTC, sleto-it commented on docs/release-notes/2.6.0.md
> +* pbm config --force-resync --wait --wait-time="5m"
Please consider to add the new `--wait-time` for all commands where it is supported under the `reference` page. Each of the commands there have a table with the available flags: `--wait-time` will need to be added there, so people who read the command reference know it exists. Add, as usual, a sentence like "Available starting with version 2.6.0.". Thanks!

2024-09-02 07:43 UTC, nastena1606 commented on docs/release-notes/2.6.0.md
> +With [snapshot-based physical backups](../features/snapshots.md) now generally available, you can use this functionality in production environments and enjoy all the benefits of faster restores from
Hi! Addressed in https://github.com/percona/pbm-docs/pull/199/files by removing the tech preview label

2024-09-02 07:44 UTC, nastena1606 commented on docs/release-notes/2.6.0.md
> +* pbm config --force-resync --wait --wait-time="5m"
Addressed in https://github.com/percona/pbm-docs/pull/192

2024-09-02 08:07 UTC, sleto-it commented on docs/release-notes/2.6.0.md
> +* pbm config --force-resync --wait --wait-time="5m"
Thanks!

2024-09-02 08:08 UTC, sleto-it commented on docs/release-notes/2.6.0.md
> +With [snapshot-based physical backups](../features/snapshots.md) now generally available, you can use this functionality in production environments and enjoy all the benefits of faster restores from
Thanks!

2024-09-02 09:04 UTC, merged