PBM-782 Release notes 1.7.0
percona/pbm-docs pull request #20
Opened 2022-03-22 13:40 UTC by nastena1606

modified:   source/conf.py
	modified:   source/release-notes.rst
	new file:   source/release-notes/1.7.0.rst

2022-03-24 11:35 UTC, spron-in requested changes

2022-03-24 11:35 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-680`: Skip TLS verification for object storage
```suggestion
* :jirabug:`PBM-680`: Skip TLS verification for object storage. This can be useful for private object storage with self-signed certificates.
```

Can we also add a link to the doc with this flag?

2022-03-24 11:35 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-734`: Add the config option to set debug log levels for S3  requests
```suggestion
* :jirabug:`PBM-734`: Users can now configure logging levels for S3 requests to debug issues with object storage
```

Can we add the link to the doc about this feature? Or at least a parameter?

2022-03-24 11:35 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-742`: Add the ability to :ref:`replay oplog <oplog-replay>` from arbitrary start time
```suggestion
* :jirabug:`PBM-742`: Add the ability to :ref:`replay oplog <oplog-replay>` from arbitrary start time. This can be used to reduce Recovery Point Objective (RPO) when database is recovered from storage-level backup, for example LVM-snapshots.
```

This should go to highlights as well.

2022-03-24 11:35 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-770`: Support configurable compression method/level for |PITR| chunks (Thanks to Damiano Albani for reporting this issue)
Can we merge PBM-770 and PBM-756 into one line? One for PITR and another one for backups. 

Something like: 
Support configurable compression method/level for backups and |PITR| chunks (Thanks to Damiano Albani for the contribution)

Also Damiano not only reported this issue, but also contributed the code :)

2022-03-24 11:35 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-750`: Make max number of S3 upload parts configurable (Thanks to Damiano Albani for reporting this issue)
```suggestion
* :jirabug:`PBM-750`: Users can configure the number of S3 multipart upload chunks to comply with various S3-compatible storage provider requirements (Thanks to Damiano Albani for the contribution)
```

2022-03-24 11:35 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-764`: Support Zstandard compression format (Thanks to Damiano Albani for reporting this issue)
```suggestion
* :jirabug:`PBM-764`: Support Zstandard compression format (Thanks to Damiano Albani for the contribution)
```

2022-03-24 11:35 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-577`: Add storage class option for S3
```suggestion
* :jirabug:`PBM-577`: It is now possible to choose an S3 storage class for granular control over various S3 tiers (Thanks to Damiano Albani for the contribution)
```

Need also to provide a link to the doc with this new option.

2022-03-24 11:35 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-680`: Skip TLS verification for object storage
This should also go to highlights. It was highly awaited feature. Users can use private object storages without workarounds.

2022-03-24 11:35 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-721`: Add the ability to configure retry upload to S3
```suggestion
* :jirabug:`PBM-721`: Fixed a bug where an upload of the backup to S3-storage was failing due to unstable network connection. |PBM| can now be configured to retry the upload with flexible timeouts.
```

add a link to parameters in docs as well?

2022-03-24 13:15 UTC, nastena1606 commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-734`: Add the config option to set debug log levels for S3  requests
Sure. I suggest moving this wording to the release highlights

2022-03-24 13:18 UTC, nastena1606 commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-770`: Support configurable compression method/level for |PITR| chunks (Thanks to Damiano Albani for reporting this issue)
I suggest merging them in the release highlights section.

2022-03-24 15:37 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* Configurable debug log levels for S3.
I think we can remove this one from highlights. It does not bring that much value.

2022-04-12 12:50 UTC, nastena1606 commented on source/release-notes/1.7.0.rst
> +* Support for :ref:`physical backups <backup-types>`. This drastically speeds up backup performance  for large databases (several terabytes). This is a technical preview feature.
I think tech preview to be consistent across all products where tech preview features are introduced

2022-04-14 17:18 UTC, olexandr-havryliak commented on source/release-notes/1.7.0.rst
> +To use physical backups with filesystem-based backup storage, the `mongod` user must be the owner of the backup directory.
It's not about ownership but about write permissions on filesystem level. Mongod user must have write permissions to backup dir

2022-04-14 17:39 UTC, nastena1606 commented on source/release-notes/1.7.0.rst
> +To use physical backups with filesystem-based backup storage, the `mongod` user must be the owner of the backup directory.
Rewritten

2022-04-14 17:51 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :ref:`Oplog replay <oplog-replay>` from the arbitrary start time. This reduces Recovery Point Objective (RPO) when database is recovered from physical backups.
```suggestion
* :ref:`Oplog replay <oplog-replay>` from the arbitrary start time. This reduces Recovery Point Objective (RPO) when database is recovered from physical or storage-level backups.
```

2022-04-14 17:51 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* Support for :ref:`physical backups <backup-types>` in |PSMDB| starting from versions 4.2.15-16 and 4.4.6-8 and higher. Physical backups drastically speed up backup performance for large databases (
```suggestion
* Support for :ref:`physical backups <backup-types>` in |PSMDB| starting from versions 4.2.15-16 and 4.4.6-8 and higher. Physical backups drastically speed up backup and restore performance for large databases (several terabytes). This is a technical preview feature. 
```

2022-04-14 17:51 UTC, spron-in commented on source/release-notes/1.7.0.rst
> +* :jirabug:`PBM-805`: Implement physical backups
```suggestion
* :jirabug:`PBM-805`: Implement physical backups which drastically speed up backup and restore performance for large databases
```

2022-04-14 18:21 UTC, olexandr-havryliak commented on source/release-notes/1.7.0.rst
> +To use physical backups with filesystem-based backup storage, the `mongod` user must be the owner of the backup directory.
Regardless how users install or upgrade pbm (from packages, binaries, manually, whatever) - two conditions must be met:
1. user from whom pbm-agent runs must have read/write permissions on mongo datadir (for physical backup/restore) 
2. user from whom pbm-agent runs must have read/write permissions on backup dir (for filesystem-based storage)
To met this conditions we have changed pbm user in our packages. Starting from this release pbm-agent daemon runs from **mongod** users, not **pbm**. So upgrade procedure from previous releases requires this pre-check
 - If pbm and mongodb was installed from our packages and filesystem storage was in use - users should manually check permissions on backup dir for write access for **mongod** user and change them if needed before upgrade
 - for custom installations - users should check conditions above

2022-04-15 12:33 UTC, sandraromanchenko approved these changes

2022-04-15 12:38 UTC, spron-in approved these changes

2022-04-15 12:40 UTC, olexandr-havryliak approved these changes

2022-04-18 14:21 UTC, merged