PBM-1376 Added SSE-S3 encryption description
percona/pbm-docs pull request #201
Opened 2024-08-20 14:56 UTC by nastena1606

2024-08-20 15:01 UTC, sandraromanchenko approved these changes

2024-08-20 15:01 UTC, sandraromanchenko commented
Looks perfect to me)

2024-08-22 08:51 UTC, radoslawszulgo requested changes

2024-08-22 08:51 UTC, radoslawszulgo commented on docs/details/storage-configuration.md
> +Percona Backup for MongoDB supports server-side encryption with Amazon S3 managed keys (SSE-S3). This is the default encryption method in Amazon AWS. All new objects added to an S3 bucket are automat
```suggestion
Percona Backup for MongoDB supports server-side encryption with Amazon S3 managed keys (SSE-S3), the default encryption method in Amazon AWS. All new objects added to an S3 bucket are automatically encrypted without impacting performance.
```

2024-08-22 08:51 UTC, radoslawszulgo commented on docs/details/storage-configuration.md
> +To use SSE-S3 encryption, specify the following following parameters in the Percona Backup for MongoDB configuration file:
```suggestion
To use SSE-S3 encryption, specify the following parameters in the Percona Backup for the MongoDB configuration file:
```

2024-09-02 08:56 UTC, merged