PBM-1388 Extended the description of how plogs are saved
percona/pbm-docs pull request #207
Opened 2024-09-10 16:28 UTC by nastena1606

modified:   docs/features/point-in-time-recovery.md

2024-09-13 08:12 UTC, boris-ilijic approved these changes

2024-09-13 08:12 UTC, boris-ilijic commented on docs/features/point-in-time-recovery.md
> +    Before backup start, point-in-time recovery routine is automatically disabled. Oplog slices are created by a backup routine during the backup creation. After the backup is complete, point-in-time
```suggestion
    Before backup starts, point-in-time recovery routine is automatically disabled. Oplog slices are created by a backup routine during the backup creation. After the backup is complete, point-in-time recovery routine is re-enabled automatically. It copies the slices taken during the backup and continues oplog slicing from the latest timestamp. 
```

2024-09-13 14:05 UTC, defbin approved these changes

2024-09-19 07:55 UTC, sandraromanchenko approved these changes

2024-09-19 08:05 UTC, radoslawszulgo commented on docs/features/point-in-time-recovery.md
> +You can, however, influence the `pbm-agent` election by assigning a priority to the `mongod` nodes. See the [Adjust node priority for oplog slices](#adjust-node-priority-for-oplog-slices) for details
```suggestion
You can manage the `pbm-agent` election by assigning a priority value to the `mongod` nodes. See the [Adjust node priority for oplog slices](#adjust-node-priority-for-oplog-slices) for details.
```

2024-09-19 08:08 UTC, radoslawszulgo commented on docs/features/point-in-time-recovery.md
> +    During a physical backup, point-in-time recovery routine is not disabled and continues to save oplog slices in parallel with a backup snapshot operation.
```suggestion
        During a physical backup, the point-in-time recovery routine is not disabled and continues to save oplog slices in parallel with a backup snapshot operation. 

```

2024-09-19 08:09 UTC, radoslawszulgo requested changes

2024-09-19 08:09 UTC, radoslawszulgo commented on docs/features/point-in-time-recovery.md
> +Thereby if a backup snapshot is large and takes hours to make, all oplog events are saved for it ensuring point-in-time recovery to any timestamp.
```suggestion
Thus, if a backup snapshot is large and takes hours to make, all oplog events are saved for it, ensuring point-in-time recovery to any timestamp.
```

2024-09-19 08:14 UTC, merged