PBM-1414 Documented changes in NumInsertionWorkers
percona/pbm-docs pull request #227
Opened 2024-11-13 09:04 UTC by nastena1606

modified:   docs/reference/pbm-commands.md
	modified:   docs/reference/restore-options.md
	modified:   docs/usage/restore.md

2024-11-27 11:07 UTC, nastena1606 commented on docs/usage/restore.md
> +        In version 2.8.0, the default number for the `numInsertionWorkers` parameter has changed. Verify your applications and adjust the configuration if needed.
```suggestion
        In version 2.8.0, the default number for the `numInsertionWorkers` parameter has changed from 10 to 1. Verify your applications and adjust the configuration if needed.
```

2024-11-27 11:21 UTC, nastena1606 commented on docs/usage/restore.md
> +    $ pbm restore <backup_name> --numInsertionWorkers 5
```suggestion
    $ pbm restore <backup_name> --num-insertion-workers-per-collection=5
```

2024-11-27 11:43 UTC, radoslawszulgo approved these changes

2024-12-04 14:07 UTC, radoslawszulgo requested changes
@nastena1606 please change the default back to 10 for now. Also adjust the "important" section -> leave just we added an option to specify the number of insertion workers per collection via command line

2024-12-04 14:07 UTC, radoslawszulgo commented on docs/reference/restore-options.md
> +*Default*: 1
Please revert to 10 now. 
```suggestion
*Default*: 10
```

2024-12-05 10:20 UTC, sandraromanchenko approved these changes

2024-12-12 16:53 UTC, merged