PBM-1226 Documented custom log path configuration
percona/pbm-docs pull request #235
Opened 2024-11-29 11:36 UTC by nastena1606

new file:   docs/manage/logpath.md
	modified:   mkdocs-base.yml

2024-12-03 10:07 UTC, sandraromanchenko requested changes

2024-12-03 10:07 UTC, sandraromanchenko commented on docs/manage/logpath.md
> +* the `stderr` file on the host where the agent is running.
```suggestion
* `STDERR` stream on the each host where the agent is running
```

2024-12-03 10:07 UTC, sandraromanchenko commented on docs/manage/logpath.md
> +If PBM cannot write to the specified file due to some error, it falls back to the `stderr` file. And you can always retrieve the logging information using the `pbm logs` command.
```suggestion
If PBM cannot write to the specified file due to some error, it falls back to `STDERR` stream. And you can always retrieve the logging information using the `pbm logs` command.
```

2024-12-03 10:24 UTC, nastena1606 commented on docs/manage/logpath.md
> +!!! admonition "Version added: [2.0.0](../release-notes/2.8.0.md)"
```suggestion
!!! admonition "Version added: [2.8.0](../release-notes/2.8.0.md)"
```

2024-12-03 13:22 UTC, sandraromanchenko approved these changes

2024-12-05 16:05 UTC, boris-ilijic reviewed
I am fine with description, but please see comments.

2024-12-05 16:05 UTC, boris-ilijic commented on docs/manage/logpath.md
> +| `LOG_OUTPUT`| `--log-output` | The output format of the log messages. Supported values are `text` (default) and `json`. |
```suggestion
| `LOG_JSON`| `--log-json` | The output format of the log messages. If specified `json` format is use and default is `text` format. |
```

2024-12-05 16:05 UTC, boris-ilijic commented on docs/manage/logpath.md
> +	$ pbm-agent --log-path=/var/log/pbm-agent.log --log-level=W --log-output=json
```suggestion
	$ pbm-agent --log-path=/var/log/pbm-agent.log --log-level=W --log-json
```

2024-12-06 10:44 UTC, boris-ilijic approved these changes
Please see additonal one

2024-12-06 10:44 UTC, boris-ilijic commented on docs/manage/logpath.md
> +	$ export LOG_json
```suggestion
	$ export LOG_JSON=1
```

2024-12-12 16:52 UTC, merged