PBM-1430 Added about a docs page
percona/pbm-docs pull request #238
Opened 2024-12-03 11:38 UTC by nastena1606

Documented the message that docs reflect the latest version

new file:   docs/about-docs.md
	modified:   docs/copyright.md
	modified:   docs/index.md
	modified:   mkdocs-base.yml

2024-12-03 21:09 UTC, radoslawszulgo requested changes

2024-12-03 21:09 UTC, radoslawszulgo commented on docs/about-docs.md
> +We encourage our users to run the latest version of PBM so that they receive all bug fixes and can enjoy all new features and improvements available with the latest version. For this reason, the docu
```suggestion
You should run the latest version of PBM to receive all bug and security fixes and benefit from the new features. For this reason, the documentation always reflects the latest PBM version. 
```

2024-12-03 21:09 UTC, radoslawszulgo commented on docs/about-docs.md
> +To track the changes in features, we indicate the version where a feature appeared or a change was introduced. Check the release notes for detailed information.
```suggestion
To track feature changes, an additional version indication is added where a feature appeared or a change was introduced. Please take a look at the release notes for detailed information.
```

2024-12-03 21:09 UTC, radoslawszulgo commented on docs/about-docs.md
> +Thank you for willing to contribute to Percona Backup for MongoDB project. Please check the [Contribution guidelines](reference/contributig.md) for  instructions.
```suggestion
Thank you for your willingness to contribute to Percona Backup for MongoDB project. Please check the [Contribution guidelines](reference/contributing.md) for instructions.
```

2024-12-03 21:09 UTC, radoslawszulgo commented on docs/copyright.md
> +Percona Backup for MongoDB documentation is (C)2016-2024 Percona LLC and/or its affiliates
Can we use a variable here to avoid hardcoded dates in all places?

2024-12-03 21:09 UTC, radoslawszulgo commented on docs/index.md
> +Percona Backup for MongoDB (PBM) is an open source and distributed solution for consistent backups and restores of [MongoDB sharded clusters and replica sets](details/deployments.md) to a specific po
```suggestion
Percona Backup for MongoDB (PBM) is an open-source and distributed solution for consistent backups and restores of [MongoDB sharded clusters and replica sets](details/deployments.md) to a specific point in time. 
```

2024-12-05 11:24 UTC, radoslawszulgo commented on docs/about-docs.md
> +Thank you for willing to contribute to Percona Backup for MongoDB project. Please check the [Contribution guidelines](reference/contributig.md) for  instructions.
+ we need to rename the "contributig.md" file ;)

2024-12-09 14:42 UTC, nastena1606 commented on docs/copyright.md
> +Percona Backup for MongoDB documentation is (C)2016-2024 Percona LLC and/or its affiliates
Done

2024-12-09 14:45 UTC, radoslawszulgo approved these changes

2024-12-09 15:03 UTC, merged