PBM-855 Release notes 1.8.0
percona/pbm-docs pull request #29
Opened 2022-06-02 13:54 UTC by nastena1606

modified:   source/conf.py
	modified:   source/release-notes.rst
	new file:   source/release-notes/1.8.0.rst

2022-06-03 11:16 UTC, dAdAbird approved these changes

2022-06-03 11:47 UTC, sandraromanchenko approved these changes

2022-06-03 19:49 UTC, spron-in requested changes

2022-06-03 19:49 UTC, spron-in commented on source/release-notes/1.8.0.rst
> +* :jirabug:`PBM-776`: Allow data restore into the replica set with a different name.
```suggestion
* :jirabug:`PBM-776`: Allow data restore into the replica set with a different name
```

2022-06-03 19:49 UTC, spron-in commented on source/release-notes/1.8.0.rst
> +* Ability to restore data to a replica set with a different name and configuration. This drastically reduces time on environment preparation for data restore.
Can we please add the link to a doc here about this new dashing feature?

2022-06-03 19:49 UTC, spron-in commented on source/release-notes/1.8.0.rst
> +* Ability to save oplog slices without the mandatory base backup. This facilitates backup / restore management from EBS-snapshots.
Same comment about the doc here.

2022-06-03 19:49 UTC, spron-in commented on source/release-notes/1.8.0.rst
> +* :jirabug:`PBM-828`: Add full config reference file to packages
I'm not sure I understand the value of this change for a user.

2022-06-03 19:49 UTC, spron-in commented on source/release-notes/1.8.0.rst
> +* :jirabug:`PBM-751`: Format timestamps according to `RFC3339 <https://datatracker.ietf.org/doc/html/rfc3339>`_ (Thanks to Damiano Albani for reporting this issue)
```suggestion
* :jirabug:`PBM-751`: Format timestamps according to `RFC3339 <https://datatracker.ietf.org/doc/html/rfc3339>`_ in `pbm list` output (Thanks to Damiano Albani for reporting this issue)
```

2022-06-03 19:49 UTC, spron-in commented on source/release-notes/1.8.0.rst
> +* :jirabug:`PBM-820`: PBM crashes on cancel backup command
```suggestion
* :jirabug:`PBM-820`: Fix a bug where PBM crashed if backup cancelled right after it started
```

2022-06-08 16:03 UTC, nastena1606 commented on source/release-notes/1.8.0.rst
> +* :jirabug:`PBM-751`: Format timestamps according to `RFC3339 <https://datatracker.ietf.org/doc/html/rfc3339>`_ (Thanks to Damiano Albani for reporting this issue)
Not only for this command but everywhere it is used. So I'd avoid mentioning pbm list here

2022-06-08 16:04 UTC, nastena1606 commented on source/release-notes/1.8.0.rst
> +* :jirabug:`PBM-820`: PBM crashes on cancel backup command
Fixed

2022-06-08 16:04 UTC, nastena1606 commented on source/release-notes/1.8.0.rst
> +* Ability to save oplog slices without the mandatory base backup. This facilitates backup / restore management from EBS-snapshots.
Done

2022-06-08 19:09 UTC, spron-in requested changes

2022-06-08 19:09 UTC, spron-in commented on source/release-notes/1.8.0.rst
> +* When you use EBS-snapshots or other tools for physical backups, you :ref:`no longer have to create a mandatory base backup in Percona Backup for MongoDB as the starting point for  Point-in-Time Rec
```suggestion
* When you use EBS-snapshots or other tools for physical backups, you :ref:`no longer have to create a mandatory base backup in Percona Backup for MongoDB as the starting point for Point-in-Time Recovery oplog slicing <pitr-oplog-only>`. This reduces time and effort on managing excessive backups and makes |PITR| from physical or storage-level backups more straightforward. 
```

"base backup" - not sure, but I think I saw us calling it base snapshot. Is it an industry term?

2022-06-08 19:09 UTC, spron-in commented on source/release-notes/1.8.0.rst
> +* :jirabug:`PBM-866`: Add the ``--wait`` flag to backup command
This one is not in highlights and value is not explained. 
There are no details in the ticket as well, so frankly I have no idea how would user understand what is it. 

@defbin please update the ticket description in JIRA.

@nastena1606 please update the description in the release notes. Like we add this --wait flag which does X and it can be useful for Y.

2022-06-08 19:09 UTC, spron-in commented on source/release-notes/1.8.0.rst
> +* :jirabug:`PBM-751`: Format timestamps according to `RFC3339 <https://datatracker.ietf.org/doc/html/rfc3339>`_ (Thanks to Damiano Albani for reporting this issue)
agree. thanks

2022-06-08 19:52 UTC, nastena1606 commented on source/release-notes/1.8.0.rst
> +* When you use EBS-snapshots or other tools for physical backups, you :ref:`no longer have to create a mandatory base backup in Percona Backup for MongoDB as the starting point for  Point-in-Time Rec
In the docs we use backup snapshot. Amended like this for consistency

2022-06-09 06:43 UTC, spron-in approved these changes

2022-06-09 12:36 UTC, sandraromanchenko approved these changes

2022-06-09 18:14 UTC, merged