PBM-883-Update intro page
percona/pbm-docs pull request #36
Opened 2022-06-23 14:11 UTC by nastena1606

Reorded the sequenca of commands and updated the use case

modified: source/intro.rst

2022-06-23 16:00 UTC, sandraromanchenko requested changes

2022-06-24 08:18 UTC, nastena1606 commented on source/intro.rst
> +To also save all events that occurred to the data between the backups, enable incremental backups:
Fixed

2022-06-24 08:54 UTC, spron-in commented on source/intro.rst
> +Since the restore and saving oplog slices are exclusive operations and cannot  run together, let’s stop oplog slicing first:
```suggestion
Since the restore and saving oplog slices are exclusive operations and cannot run together, let’s stop oplog slicing first:
```

2022-06-24 08:56 UTC, spron-in approved these changes

2022-06-27 09:52 UTC, LenzGr commented on source/intro.rst
> +To also save all events that occurred to the data between the backups, enable saving oplog slices:
```suggestion
To also save all events that occurred to the data while the backup was running, enable saving oplog slices:
```

2022-06-27 09:53 UTC, LenzGr commented on source/intro.rst
> +The output lists the valid time ranges for the restore. The desired time (February 7th, 03:00 UTC) falls within the ``2021-02-03T08:08:36Z-2021-02-09T12:20:23Z`` range, so let’s restore the database
```suggestion
The output lists the valid time ranges for the restore. The desired time (February 7th, 03:00 UTC) falls within the ``2021-02-03T08:08:36Z-2021-02-09T12:20:23Z`` range, so let’s restore the state of database back to that time. 
```

2022-06-27 09:54 UTC, nastena1606 commented on source/intro.rst
> +To also save all events that occurred to the data between the backups, enable saving oplog slices:
Oplog that relates to the backup snapshot is saved together with that snapshot. This is about oplog events that occurred between the snapshots.

2022-06-27 09:59 UTC, LenzGr commented on source/intro.rst
> +To also save all events that occurred to the data between the backups, enable saving oplog slices:
Ah, I see. Then it might make sense to explain this behavior in the paragraph above that explains the `pbm backup` command?

2022-06-29 10:03 UTC, merged