PBM-965 Release notes 2.0.1
percona/pbm-docs pull request #56
Opened 2022-10-03 11:09 UTC by nastena1606

modified:   docs/release-notes.md
	new file:   docs/release-notes/2.0.1.md
	modified:   mkdocs-base.yml

2022-10-07 08:05 UTC, sandraromanchenko requested changes

2022-10-07 08:05 UTC, sandraromanchenko commented on docs/release-notes/2.0.1.md
> +- [PBM-949](https://jira.percona.com/browse/PBM-949): Improve handling of arbiter, hidden, delayed and non-voting nodes
Should we maybe rename the ticket as nothing is changed for hidden, delayed and non-voting nodes?

2022-10-07 08:36 UTC, nastena1606 commented on docs/release-notes/2.0.1.md
> +- [PBM-949](https://jira.percona.com/browse/PBM-949): Improve handling of arbiter, hidden, delayed and non-voting nodes
Done

2022-10-07 08:37 UTC, sandraromanchenko approved these changes

2022-10-09 07:10 UTC, janwieremjewicz approved these changes

2022-10-12 09:07 UTC, merged