PBM-999 Incremental backups
percona/pbm-docs pull request #66
Opened 2022-12-19 17:05 UTC by nastena1606

modified:   docs/reference/glossary.md
	modified:   docs/reference/pbm-commands.md
	modified:   mkdocs-base.yml
	deleted:    netlify.toml
docs/usage/incremental-backup.md

2022-12-21 12:11 UTC, sandraromanchenko requested changes

2022-12-21 12:11 UTC, sandraromanchenko commented on docs/usage/incremental-backup.md
> +Percona Backup for MongoDB tracks the backup history only on the node where the base incremental backup was taken. This means that subsequent incremental backups must always be run on that very node.
No need to set priorities, it should work as is now. 
from spec
PBM will try to schedule the backup on the node that made a previous one. It’s done by bumping the node’s priority score. It will be done only in case of no priorities are set in the config. PBM will follow config scores should the user set it (hence no bumping of the node’s score).

2022-12-22 09:34 UTC, nastena1606 commented on docs/usage/incremental-backup.md
> +Restore flow from an incremental backup is the same as the restore from a full physical backup: specify the timestamp for the `pbm restore` command:
Updated

2022-12-22 09:34 UTC, nastena1606 commented on docs/usage/incremental-backup.md
> +pbm restore 2022-11-03T11:09:04Z
Updated

2022-12-26 09:48 UTC, sandraromanchenko approved these changes

2023-01-11 16:14 UTC, dAdAbird commented on docs/usage/incremental-backup.md
> +    2022-11-23T16:15:20Z 883.51KB <incremental> [restore_to_time: 2022-11-23T16:15:22Z]
```suggestion
    2022-11-25T14:00:22Z 228.30GB <incremental> [restore_to_time: 2022-11-25T14:00:24Z]
    2022-11-24T14:45:53Z 220.13GB <physical> [restore_to_time: 2022-11-24T14:45:55Z]
```

I'd rearrange it like that so the benefits of incremental backups are more obvious.

2023-01-11 16:14 UTC, dAdAbird commented on docs/usage/incremental-backup.md
> +If the node with the base incremental backup is down or unavailable, you must start the incremental backup chain anew on another node.
I'll add here that PBM will always try to schedule subsequent backups on the same node. So the user shouldn't bother with this.

2023-01-11 16:14 UTC, dAdAbird commented on docs/usage/restore.md
> +To restore a backup, use the [`pbm restore`](../reference/pbm-commands.md#pbm-restore) command supplying the backup name from which you intend to restore. Percona Backup for MongoDB identifies the ty
```suggestion
To restore a backup, use the [`pbm restore`](../reference/pbm-commands.md#pbm-restore) command supplying the backup name from which you intend to restore. Percona Backup for MongoDB identifies the type of the backup (physical, logical or incremental) and restores the database up to the [backup completion time](../reference/glossary.md#completion-time) (available in `pbm list` output as of version 1.4.0).
```

2023-01-11 16:51 UTC, nastena1606 commented on docs/usage/restore.md
> +To restore a backup, use the [`pbm restore`](../reference/pbm-commands.md#pbm-restore) command supplying the backup name from which you intend to restore. Percona Backup for MongoDB identifies the ty
Added

2023-01-11 17:06 UTC, sandraromanchenko approved these changes

2023-01-11 17:08 UTC, nastena1606 commented on docs/usage/incremental-backup.md
> +If the node with the base incremental backup is down or unavailable, you must start the incremental backup chain anew on another node.
Done

2023-01-11 17:08 UTC, dAdAbird approved these changes

2023-01-11 17:08 UTC, merged