PBM-1011 Release notes 2.0.3
percona/pbm-docs pull request #69
Opened 2022-12-22 16:00 UTC by nastena1606

2022-12-26 13:54 UTC, sandraromanchenko requested changes

2022-12-26 13:54 UTC, sandraromanchenko commented on docs/release-notes/2.0.3.md
> +* [PBM-1006](https://jira.percona.com/browse/PBM-1006) - Fix the `pbm-agent` crash during physical restore by initializing the logger for storage
please also add [PBM-1003] (https://jira.percona.com/browse/PBM-1003)

2023-01-10 11:13 UTC, sandraromanchenko requested changes

2023-01-10 11:13 UTC, sandraromanchenko commented on docs/release-notes/2.0.3.md
> +* [PBM-1012](https://jira.percona.com/browse/PBM-1012) - Collection is not dropped during selective oplog replay on create command
remove this one please, it's decided to move it to the next version

2023-01-10 12:01 UTC, janwieremjewicz reviewed
Not sure about the IB abbreviation. Other than this is ok

2023-01-10 12:01 UTC, janwieremjewicz commented on docs/release-notes/2.0.3.md
> +* [Incremental physical backups](usage/incremental-backup.md) enable you to reduce storage costs and facilitate data safety for business crucial data. By saving only the differences results in faster
Did we introduce the abbreviation IB?

2023-01-10 12:38 UTC, nastena1606 commented on docs/release-notes/2.0.3.md
> +* [Incremental physical backups](usage/incremental-backup.md) enable you to reduce storage costs and facilitate data safety for business crucial data. By saving only the differences results in faster
No, we didn't

2023-01-10 12:39 UTC, nastena1606 commented on docs/release-notes/2.0.3.md
> +* [PBM-1012](https://jira.percona.com/browse/PBM-1012) - Collection is not dropped during selective oplog replay on create command
Fixed

2023-01-10 12:47 UTC, sandraromanchenko approved these changes

2023-01-11 16:18 UTC, dAdAbird approved these changes

2023-01-11 17:11 UTC, merged