PBM-1042 Added option to define custom path for mongod
percona/pbm-docs pull request #85
Opened 2023-02-15 14:31 UTC by nastena1606

2023-02-20 13:35 UTC, janwieremjewicz approved these changes

2023-02-20 14:01 UTC, sandraromanchenko requested changes

2023-02-20 14:01 UTC, sandraromanchenko commented on docs/usage/restore.md
> +During physical restores, Percona Backup for MongoDB performs several internal restarts of the database. By default, it uses the location of the `mongod` binaries from the `$PATH` variable to access
remove "internal"

2023-02-20 19:34 UTC, nastena1606 commented on docs/reference/restore-options.md
> +The custom path to `mongod` binaries. When undefined, Percona Backup for MongoDB uses the default path to make internal database restarts during physical restore.
Fixed

2023-02-20 19:34 UTC, nastena1606 commented on docs/reference/restore-options.md
> +The list of custom paths to `mongod` binaries on every node. Percona Backup for MongoDB uses the vales to make internal restarts of the database during physical restore.
Fixed the typo. Why the default when this is the custom path?

2023-02-20 19:35 UTC, nastena1606 commented on docs/usage/restore.md
> +During physical restores, Percona Backup for MongoDB performs several internal restarts of the database. By default, it uses the location of the `mongod` binaries from the `$PATH` variable to access
Done

2023-02-20 19:35 UTC, nastena1606 commented on docs/usage/restore.md
> +As the precondition to a physical restore, shut down all `mongos` nodes to stop clients from accessing the database while restore is in progress. This ensures that the final restored data doesn’t dif
Updated

2023-02-21 09:11 UTC, sandraromanchenko commented on docs/reference/restore-options.md
> +The list of custom paths to `mongod` binaries on every node. Percona Backup for MongoDB uses the vales to make internal restarts of the database during physical restore.
Sorry, my bad, I've read it the same way as above option. It's ok now.

2023-02-21 09:20 UTC, sandraromanchenko approved these changes

2023-02-21 16:42 UTC, merged