PBM-875 Described configuration options for concurrent download
percona/pbm-docs pull request #90
Opened 2023-04-05 10:27 UTC by nastena1606

2023-04-10 14:09 UTC, sandraromanchenko approved these changes

2023-04-12 17:36 UTC, sandraromanchenko requested changes

2023-04-12 17:36 UTC, sandraromanchenko commented on docs/usage/restore.md
> +    You can speed up the restore by setting up parallel download of data chunks from the S3 storage. Thereby you can reach up to 7 times faster performance during the restore. Read more about benchma
```suggestion
    You can speed up the restore by setting up parallel download of data chunks from the S3 storage.
```
It shouldn't be set up specifically, feature works out of the box. Can it be re-phased to emphasize that feature is introduced in current release and will speed up restore to X times, but if fine tuning is required - then options can be used?

2023-04-12 18:24 UTC, nastena1606 commented on docs/usage/restore.md
> +    You can speed up the restore by setting up parallel download of data chunks from the S3 storage. Thereby you can reach up to 7 times faster performance during the restore. Read more about benchma
Amended

2023-04-12 18:26 UTC, sandraromanchenko approved these changes

2023-04-18 11:13 UTC, merged