PBM-1007 Support of selective backup for sharded collections
percona/pbm-docs pull request #91
Opened 2023-04-05 10:27 UTC by nastena1606

2023-04-10 14:01 UTC, sandraromanchenko requested changes

2023-04-10 14:01 UTC, sandraromanchenko commented on docs/features/selective-backup.md
> +7. Point-in-time recovery is not supported for sharded collections.
```suggestion
7. Selective point-in-time recovery is not supported.
```

2023-04-11 15:20 UTC, defbin requested changes

2023-04-11 15:20 UTC, defbin commented on docs/features/selective-backup.md
> +During the restore, the reverse process occurs: a `pbm-agent` on each shard restores its saved subset of documents plus the oplog that relates to the specified namespaces. On the config server replic
```suggestion
During the restore, the reverse process occurs:
- a `pbm-agent` on each shard restores only the selected collections and replays the oplog but only for the selected collections. Ops for other namespaces are not replayed.
- on the config server replica set, the `pbm-agent` restores the router configuration for only selected shared collections. Other router configurations for existing databases, collections, and chunks are not modified.

Restore for sharded timeseries is not supported.
```

2023-04-11 15:20 UTC, defbin commented on docs/features/selective-backup.md
> +Note that selective backups and restores operate only with data, the cluster configuration is not restored. Therefore, we recommended to restore the databases/collections on the same environment.
I do not understand it. Do you mean we restore databases, collections, and router config but do not restore cluster/topology related settings?

2023-04-11 15:20 UTC, defbin commented on docs/features/selective-backup.md
> +During the selective restore, the cluster topology is restored to the state it had when the backup was made. This means if shard A was the primary one during backup, it will be restored as the primar
```suggestion
During the selective restore, the primary shards for selected databases are set to the shards that were in backup time. This means if shard A was the primary shard for a database during backup, it will be set as the primary shard for the database even if you moved the database (changed primary shard) to B between the backup and the restore time. All non-sharded collections will be restored on A; however, they will not be deleted from B. `pbm-agent` drops collections on a shard only when it restores the collections on the shard. You'll need to take the necessary actions (cleanup or move the primary back to B) to maintain them. 
```

2023-04-11 17:14 UTC, defbin commented on docs/features/selective-backup.md
> +Note that selective backups and restores operate only with data, the cluster configuration is not restored. Therefore, we recommended to restore the databases/collections on the same environment.
Please, rephrase your note in the doc. It's not clear. For example, in a similar form as I asked you

2023-04-12 17:46 UTC, sandraromanchenko approved these changes
Looks good to me with @defbin suggestions

2023-04-14 10:23 UTC, sandraromanchenko approved these changes

2023-04-18 11:14 UTC, merged