PBM-850 Documented cleanup of backup storage
percona/pbm-docs pull request #92
Opened 2023-04-05 19:29 UTC by nastena1606

docs/reference/pbm-commands.md
	modified:   docs/usage/delete-backup.md
	modified:   docs/usage/schedule-backup.md

2023-04-13 15:30 UTC, sandraromanchenko commented on docs/usage/delete-backup.md
> +    * When point-in-time recovery is enabled and you specify the timestamp greater than the `restore_to_time` for the most recent backup, PBM keeps this backup and all oplog slices deriving from it t
```suggestion
    * When point-in-time recovery is enabled and you specify the timestamp greater than the `restore_to_time` for the most recent logical backup, PBM keeps this backup and all oplog slices deriving from it to ensure point-in-time recovery. 
```

2023-04-14 06:17 UTC, nastena1606 commented on docs/usage/delete-backup.md
> +    * When point-in-time recovery is enabled and you specify the timestamp greater than the `restore_to_time` for the most recent backup, PBM keeps this backup and all oplog slices deriving from it t
Updated

2023-04-14 06:17 UTC, nastena1606 commented on docs/usage/delete-backup.md
> +* **Incremental physical backups** are deleted up to the specified time if the timestamp doesn't fall within the backup chain. If it does, PBM keeps the most recent base incremental backup and the wh
Updated

2023-04-14 06:39 UTC, sandraromanchenko approved these changes

2023-04-14 07:36 UTC, defbin requested changes

2023-04-14 07:36 UTC, defbin commented on docs/reference/pbm-commands.md
`--dry-run` - "Report but do not delete"

2023-04-14 07:42 UTC, defbin commented
Also missed case: if there is a full logical, physical, or incremental backup at the `older-than` time, PBM does not exclude from deletion the most recent (before `older-than`) full logical backup and its oplog. The incremental chain is still excluded if needed.
The reason is that it is possible to fully restore data to the `older-than` time using any full backup of any type

2023-04-14 09:22 UTC, sandraromanchenko approved these changes

2023-04-18 11:15 UTC, merged