PBM-955 Restore of data-at-rest encrypted data
percona/pbm-docs pull request #93
Opened 2023-04-06 08:07 UTC by nastena1606

2023-04-10 15:21 UTC, sandraromanchenko requested changes

2023-04-10 15:21 UTC, sandraromanchenko commented on docs/features/physical.md
> +
These 2 steps are the same - just leave the first one

2023-04-10 15:21 UTC, sandraromanchenko commented on docs/features/physical.md
> +If you run the Percona Server for MongoDB version **before** 4.4.19-19, 5.0.15-13, 6.0.5-4, and PBM before 2.0.1, and use the Vault server, consider using the following restore scenario:
It's technically possible to use instruction above - however after restore it won't be possible to rotate key, we should mention that

2023-04-11 12:24 UTC, nastena1606 commented on docs/features/physical.md
> +If you run the Percona Server for MongoDB version **before** 4.4.19-19, 5.0.15-13, 6.0.5-4, and PBM before 2.0.1, and use the Vault server, consider using the following restore scenario:
Updated the doc

2023-04-12 18:01 UTC, sandraromanchenko requested changes
Small changes, the rest is perfect ^_^

2023-04-12 18:01 UTC, sandraromanchenko commented on docs/features/physical.md
> +In Percona Server for MongoDB version **before** 4.4.19-19, 5.0.15-13, 6.0.5-4 with the Vault server used for data-at-rest encryption, the master key rotation with the same key is not supported. If y
```suggestion
In Percona Server for MongoDB version **before** 4.4.19-19, 5.0.15-13, 6.0.5-4 with the Vault server used for data-at-rest encryption, the master key rotation with the same key for used for 2+ nodes is not supported. If you run these versions of Percona Server for MongoDB and PBM before 2.1.0, consider using the scenario where PBM restores the data on one node of every replica set. The remaining nodes receive the data during the initial sync. 
```

2023-04-12 18:11 UTC, nastena1606 commented on docs/features/physical.md
> +In Percona Server for MongoDB version **before** 4.4.19-19, 5.0.15-13, 6.0.5-4 with the Vault server used for data-at-rest encryption, the master key rotation with the same key is not supported. If y
Fixed

2023-04-12 18:25 UTC, sandraromanchenko approved these changes

2023-04-18 11:16 UTC, merged